[package]
name = "pico8-to-lua"
version = "0.1.0"
edition = "2024"

[dependencies]
find-matching-bracket = "0.2.0"
lazy-regex = { version = "3.0", default-features = false, features = ["lite"] }
regex-lite = "0.1.6"
